--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/pixelwhiz/Times
build-by-default: true
branches:
  - master
projects:
  Times:
    path: ""
    lint: false
    icon: "./assets/icon.png"
...
