---
name: Times
version: 0.0.1
main: pixelwhiz\times\Loader
api: 5.19.0
src-namespace-prefix: pixelwhiz\times
author: pixelwhiz
permissions:
  times.cmd:
    description: Allows users to set the world day and time
    default: op
...
