---
name: Times
version: 2.0
main: pixelwhiz\times\Loader
api: 5.0.0
src-namespace-prefix: pixelwhiz\times
author: pixelwhiz
website: https://github.com/pixelwhiz/Times.git
permissions:
  times.cmd:
    description: Allows users to set the world day and time
    default: op
...
